### ISSUE TITLE
Missing fst2htklat.sh

### ISSUE THREAD

**Issue by Ore-an** [qiujiali/lattice-rescore#1]
Hi, I was trying to reproduce the results in you paper, but the repo is missing the script fst2htklat.sh. It gets called by your version of convert_slf_parallel.sh, but it doesn't seem to be a part of Kaldi or HTK. Could you upload it or explain what it does?

**Comment by qiujiali** [comment]
Hi, thanks for reporting this issue. I have created PR #2 which contains the missing scripts. Please check out if this works. This series of scripts converts Kaldi lattices in FST into readable HTK lattices in SLF, which are then used for rescoring.

**Comment by Ore-an** [comment]
Thanks. It works now.
